"""initial_schema

Revision ID: 4be230e39696
Revises: 
Create Date: 2026-03-17 15:14:51.748272
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4be230e39696'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_run_logs',
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('run_type', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.String(length=50), nullable=False),
    sa.Column('completed_at', sa.String(length=50), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_succeeded', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('run_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant isolation key — enforced by PostgreSQL RLS'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_run_logs_tenant_id'), 'agent_run_logs', ['tenant_id'], unique=False)
    op.create_index('ix_agent_run_tenant_agent', 'agent_run_logs', ['tenant_id', 'agent_name'], unique=False)
    op.create_index('ix_agent_run_tenant_started', 'agent_run_logs', ['tenant_id', 'started_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant isolation key — enforced by PostgreSQL RLS'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index('ix_audit_tenant_created', 'audit_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_audit_tenant_entity', 'audit_logs', ['tenant_id', 'entity_type', 'entity_id'], unique=False)
    op.create_table('briefings',
    sa.Column('briefing_date', sa.Date(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('recipient_role', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('delivered_via', sa.String(length=20), nullable=True),
    sa.Column('delivered_at', sa.String(length=50), nullable=True),
    sa.Column('opened_at', sa.String(length=50), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('generation_time_ms', sa.Integer(), nullable=True),
    sa.Column('data_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant isolation key — enforced by PostgreSQL RLS'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_briefing_tenant_date', 'briefings', ['tenant_id', 'briefing_date'], unique=False)
    op.create_index(op.f('ix_briefings_tenant_id'), 'briefings', ['tenant_id'], unique=False)
    op.create_table('connector_configs',
    sa.Column('connector_type', sa.Enum('D365_FO', 'SAP_B1', 'AX_2012', 'SALESFORCE', 'CSV_IMPORT', 'DEMO', name='connectortype'), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('field_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sync_schedule', sa.String(length=100), nullable=True),
    sa.Column('last_sync_at', sa.String(length=50), nullable=True),
    sa.Column('last_sync_status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'PARTIAL', name='syncstatus'), nullable=True),
    sa.Column('last_sync_records', sa.Integer(), nullable=True),
    sa.Column('last_sync_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant isolation key — enforced by PostgreSQL RLS'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'connector_type', name='uq_connector_tenant_type')
    )
    op.create_index(op.f('ix_connector_configs_tenant_id'), 'connector_configs', ['tenant_id'], unique=False)
    op.create_table('customers',
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('source_system', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('name_ar', sa.String(length=500), nullable=True),
    sa.Column('trade_name', sa.String(length=500), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BLOCKED', 'CREDIT_HOLD', 'PROSPECT', name='customerstatus'), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('segment', sa.String(length=100), nullable=True),
    sa.Column('territory', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('credit_limit_currency', sa.String(length=3), nullable=True),
    sa.Column('credit_utilization', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('credit_hold', sa.Boolean(), nullable=True),
    sa.Column('credit_hold_threshold', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('churn_probability', sa.Float(), nullable=True),
    sa.Column('predicted_dso', sa.Float(), nullable=True),
    sa.Column('ecl_stage', sa.Enum('STAGE_1', 'STAGE_2', 'STAGE_3', name='eclstage'), nullable=True),
    sa.Column('ecl_provision_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('assigned_collector_id', sa.UUID(), nullable=True),
    sa.Column('assigned_sales_rep_id', sa.UUID(), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('data_quality_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_synced_at', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant isolation key — enforced by PostgreSQL RLS'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'external_id', 'source_system', name='uq_customer_external')
    )
    op.create_index('ix_customer_tenant_name', 'customers', ['tenant_id', 'name'], unique=False)
    op.create_index('ix_customer_tenant_status', 'customers', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_table('data_quality_records',
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('source_system', sa.String(length=50), nullable=True),
    sa.Column('sync_batch_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('CLEAN', 'WARNING', 'QUARANTINED', 'ENRICHED', name='dataqualitystatus'), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('validation_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dedup_matches', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('normalization_changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('anomalies_detected', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enrichment_applied', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_quarantined', sa.Boolean(), nullable=True),
    sa.Column('quarantine_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.String(length=50), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant isolation key — enforced by PostgreSQL RLS'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_records_tenant_id'), 'data_quality_records', ['tenant_id'], unique=False)
    op.create_index('ix_dq_tenant_entity', 'data_quality_records', ['tenant_id', 'entity_type'], unique=False)
    op.create_table('ocr_documents',
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('extracted_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('processed_at', sa.String(length=50), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.String(length=50), nullable=True),
    sa.Column('review_corrections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('linked_entity_type', sa.String(length=100), nullable=True),
    sa.Column('linked_entity_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant isolation key — enforced by PostgreSQL RLS'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_documents_tenant_id'), 'ocr_documents', ['tenant_id'], unique=False)
    op.create_index('ix_ocr_tenant_type', 'ocr_documents', ['tenant_id', 'document_type'], unique=False)
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'TRIAL', 'SUSPENDED', 'CANCELLED', name='tenantstatus'), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('default_currency', sa.String(length=3), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('subscription_tier', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'TENANT_ADMIN', 'CFO', 'FINANCE_MANAGER', 'COLLECTOR', 'SALES_REP', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_sso', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sso_provider', sa.String(length=50), nullable=True),
    sa.Column('sso_subject_id', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('territory_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('last_login_at', sa.String(length=50), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant isolation key — enforced by PostgreSQL RLS'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_user_tenant_email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index('ix_users_tenant_role', 'users', ['tenant_id', 'role'], unique=False)
    op.create_table('credit_limit_requests',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=False),
    sa.Column('current_limit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('requested_limit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('ai_recommended_limit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('ai_risk_assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'AUTO_APPROVED', name='creditapprovalstatus'), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_limit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant isolation key — enforced by PostgreSQL RLS'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_limit_requests_tenant_id'), 'credit_limit_requests', ['tenant_id'], unique=False)
    op.create_index('ix_credit_req_tenant_status', 'credit_limit_requests', ['tenant_id', 'approval_status'], unique=False)
    op.create_table('invoices',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('source_system', sa.String(length=50), nullable=True),
    sa.Column('po_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('posting_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('amount_remaining', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'DISPUTED', 'WRITTEN_OFF', 'CREDIT_NOTE', name='invoicestatus'), nullable=False),
    sa.Column('days_overdue', sa.Integer(), nullable=True),
    sa.Column('aging_bucket', sa.String(length=20), nullable=True),
    sa.Column('predicted_pay_date', sa.Date(), nullable=True),
    sa.Column('payment_probability', sa.Float(), nullable=True),
    sa.Column('line_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ocr_document_id', sa.UUID(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant isolation key — enforced by PostgreSQL RLS'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'invoice_number', name='uq_invoice_number')
    )
    op.create_index('ix_invoice_customer', 'invoices', ['tenant_id', 'customer_id'], unique=False)
    op.create_index('ix_invoice_tenant_due', 'invoices', ['tenant_id', 'due_date'], unique=False)
    op.create_index('ix_invoice_tenant_status', 'invoices', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.create_table('collection_activities',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('collector_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.Enum('EMAIL_REMINDER', 'SMS_REMINDER', 'PHONE_CALL', 'ESCALATION', 'PROMISE_TO_PAY', 'LEGAL_NOTICE', 'WRITE_OFF_REQUEST', name='collectionaction'), nullable=False),
    sa.Column('action_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ptp_date', sa.Date(), nullable=True),
    sa.Column('ptp_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ptp_fulfilled', sa.Boolean(), nullable=True),
    sa.Column('is_ai_suggested', sa.Boolean(), nullable=True),
    sa.Column('ai_priority_score', sa.Float(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant isolation key — enforced by PostgreSQL RLS'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_activities_tenant_id'), 'collection_activities', ['tenant_id'], unique=False)
    op.create_index('ix_collection_tenant_customer', 'collection_activities', ['tenant_id', 'customer_id'], unique=False)
    op.create_table('disputes',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('dispute_number', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Enum('PRICING', 'QUANTITY', 'QUALITY', 'DELIVERY', 'DUPLICATE', 'WRONG_PRODUCT', 'DAMAGED', 'NOT_RECEIVED', 'TERMS', 'OTHER', name='disputereason'), nullable=False),
    sa.Column('reason_detail', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_REVIEW', 'ESCALATED', 'RESOLVED', 'REJECTED', 'CREDIT_ISSUED', name='disputestatus'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('assigned_department', sa.String(length=100), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('escalated_to_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('resolution_type', sa.String(length=50), nullable=True),
    sa.Column('resolution_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.String(length=50), nullable=True),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('sla_due_date', sa.Date(), nullable=True),
    sa.Column('sla_breached', sa.Boolean(), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant isolation key — enforced by PostgreSQL RLS'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dispute_customer', 'disputes', ['tenant_id', 'customer_id'], unique=False)
    op.create_index('ix_dispute_tenant_status', 'disputes', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_disputes_tenant_id'), 'disputes', ['tenant_id'], unique=False)
    op.create_table('payments',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('source_system', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('payment_method', sa.Enum('BANK_TRANSFER', 'CHECK', 'CASH', 'CREDIT_CARD', 'ONLINE', 'OTHER', name='paymentmethod'), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('bank_reference', sa.String(length=100), nullable=True),
    sa.Column('is_matched', sa.Boolean(), nullable=True),
    sa.Column('matched_at', sa.String(length=50), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant isolation key — enforced by PostgreSQL RLS'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_customer', 'payments', ['tenant_id', 'customer_id'], unique=False)
    op.create_index('ix_payment_tenant_date', 'payments', ['tenant_id', 'payment_date'], unique=False)
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    op.create_table('write_offs',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('write_off_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('ecl_stage', sa.Enum('STAGE_1', 'STAGE_2', 'STAGE_3', name='eclstage'), nullable=True),
    sa.Column('ecl_probability', sa.Float(), nullable=True),
    sa.Column('provision_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'AUTO_APPROVED', name='creditapprovalstatus'), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.String(length=50), nullable=True),
    sa.Column('is_reversed', sa.Boolean(), nullable=True),
    sa.Column('reversed_at', sa.String(length=50), nullable=True),
    sa.Column('reversed_by_id', sa.UUID(), nullable=True),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant isolation key — enforced by PostgreSQL RLS'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_write_offs_tenant_id'), 'write_offs', ['tenant_id'], unique=False)
    op.create_index('ix_writeoff_tenant_customer', 'write_offs', ['tenant_id', 'customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_writeoff_tenant_customer', table_name='write_offs')
    op.drop_index(op.f('ix_write_offs_tenant_id'), table_name='write_offs')
    op.drop_table('write_offs')
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_index('ix_payment_tenant_date', table_name='payments')
    op.drop_index('ix_payment_customer', table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_disputes_tenant_id'), table_name='disputes')
    op.drop_index('ix_dispute_tenant_status', table_name='disputes')
    op.drop_index('ix_dispute_customer', table_name='disputes')
    op.drop_table('disputes')
    op.drop_index('ix_collection_tenant_customer', table_name='collection_activities')
    op.drop_index(op.f('ix_collection_activities_tenant_id'), table_name='collection_activities')
    op.drop_table('collection_activities')
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_index('ix_invoice_tenant_status', table_name='invoices')
    op.drop_index('ix_invoice_tenant_due', table_name='invoices')
    op.drop_index('ix_invoice_customer', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_credit_req_tenant_status', table_name='credit_limit_requests')
    op.drop_index(op.f('ix_credit_limit_requests_tenant_id'), table_name='credit_limit_requests')
    op.drop_table('credit_limit_requests')
    op.drop_index('ix_users_tenant_role', table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index('ix_ocr_tenant_type', table_name='ocr_documents')
    op.drop_index(op.f('ix_ocr_documents_tenant_id'), table_name='ocr_documents')
    op.drop_table('ocr_documents')
    op.drop_index('ix_dq_tenant_entity', table_name='data_quality_records')
    op.drop_index(op.f('ix_data_quality_records_tenant_id'), table_name='data_quality_records')
    op.drop_table('data_quality_records')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_index('ix_customer_tenant_status', table_name='customers')
    op.drop_index('ix_customer_tenant_name', table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_connector_configs_tenant_id'), table_name='connector_configs')
    op.drop_table('connector_configs')
    op.drop_index(op.f('ix_briefings_tenant_id'), table_name='briefings')
    op.drop_index('ix_briefing_tenant_date', table_name='briefings')
    op.drop_table('briefings')
    op.drop_index('ix_audit_tenant_entity', table_name='audit_logs')
    op.drop_index('ix_audit_tenant_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_agent_run_tenant_started', table_name='agent_run_logs')
    op.drop_index('ix_agent_run_tenant_agent', table_name='agent_run_logs')
    op.drop_index(op.f('ix_agent_run_logs_tenant_id'), table_name='agent_run_logs')
    op.drop_table('agent_run_logs')
    # ### end Alembic commands ###
