"""add_tenant_fk

Revision ID: 82bd4b8954e9
Revises: 4be230e39696
Create Date: 2026-03-17 15:25:32.094648
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82bd4b8954e9'
down_revision: Union[str, None] = '4be230e39696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_run_logs', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant isolation key -- enforced by PostgreSQL RLS',
               existing_comment='Tenant isolation key — enforced by PostgreSQL RLS',
               existing_nullable=False)
    op.create_foreign_key(None, 'agent_run_logs', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('audit_logs', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant isolation key -- enforced by PostgreSQL RLS',
               existing_comment='Tenant isolation key — enforced by PostgreSQL RLS',
               existing_nullable=False)
    op.create_foreign_key(None, 'audit_logs', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('briefings', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant isolation key -- enforced by PostgreSQL RLS',
               existing_comment='Tenant isolation key — enforced by PostgreSQL RLS',
               existing_nullable=False)
    op.create_foreign_key(None, 'briefings', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('collection_activities', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant isolation key -- enforced by PostgreSQL RLS',
               existing_comment='Tenant isolation key — enforced by PostgreSQL RLS',
               existing_nullable=False)
    op.create_foreign_key(None, 'collection_activities', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('connector_configs', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant isolation key -- enforced by PostgreSQL RLS',
               existing_comment='Tenant isolation key — enforced by PostgreSQL RLS',
               existing_nullable=False)
    op.create_foreign_key(None, 'connector_configs', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('credit_limit_requests', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant isolation key -- enforced by PostgreSQL RLS',
               existing_comment='Tenant isolation key — enforced by PostgreSQL RLS',
               existing_nullable=False)
    op.create_foreign_key(None, 'credit_limit_requests', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('customers', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant isolation key -- enforced by PostgreSQL RLS',
               existing_comment='Tenant isolation key — enforced by PostgreSQL RLS',
               existing_nullable=False)
    op.create_foreign_key(None, 'customers', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('data_quality_records', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant isolation key -- enforced by PostgreSQL RLS',
               existing_comment='Tenant isolation key — enforced by PostgreSQL RLS',
               existing_nullable=False)
    op.create_foreign_key(None, 'data_quality_records', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('disputes', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant isolation key -- enforced by PostgreSQL RLS',
               existing_comment='Tenant isolation key — enforced by PostgreSQL RLS',
               existing_nullable=False)
    op.create_foreign_key(None, 'disputes', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('invoices', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant isolation key -- enforced by PostgreSQL RLS',
               existing_comment='Tenant isolation key — enforced by PostgreSQL RLS',
               existing_nullable=False)
    op.create_foreign_key(None, 'invoices', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ocr_documents', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant isolation key -- enforced by PostgreSQL RLS',
               existing_comment='Tenant isolation key — enforced by PostgreSQL RLS',
               existing_nullable=False)
    op.create_foreign_key(None, 'ocr_documents', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('payments', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant isolation key -- enforced by PostgreSQL RLS',
               existing_comment='Tenant isolation key — enforced by PostgreSQL RLS',
               existing_nullable=False)
    op.create_foreign_key(None, 'payments', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant isolation key -- enforced by PostgreSQL RLS',
               existing_comment='Tenant isolation key — enforced by PostgreSQL RLS',
               existing_nullable=False)
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('write_offs', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant isolation key -- enforced by PostgreSQL RLS',
               existing_comment='Tenant isolation key — enforced by PostgreSQL RLS',
               existing_nullable=False)
    op.create_foreign_key(None, 'write_offs', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'write_offs', type_='foreignkey')
    op.alter_column('write_offs', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant isolation key — enforced by PostgreSQL RLS',
               existing_comment='Tenant isolation key -- enforced by PostgreSQL RLS',
               existing_nullable=False)
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant isolation key — enforced by PostgreSQL RLS',
               existing_comment='Tenant isolation key -- enforced by PostgreSQL RLS',
               existing_nullable=False)
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.alter_column('payments', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant isolation key — enforced by PostgreSQL RLS',
               existing_comment='Tenant isolation key -- enforced by PostgreSQL RLS',
               existing_nullable=False)
    op.drop_constraint(None, 'ocr_documents', type_='foreignkey')
    op.alter_column('ocr_documents', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant isolation key — enforced by PostgreSQL RLS',
               existing_comment='Tenant isolation key -- enforced by PostgreSQL RLS',
               existing_nullable=False)
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.alter_column('invoices', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant isolation key — enforced by PostgreSQL RLS',
               existing_comment='Tenant isolation key -- enforced by PostgreSQL RLS',
               existing_nullable=False)
    op.drop_constraint(None, 'disputes', type_='foreignkey')
    op.alter_column('disputes', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant isolation key — enforced by PostgreSQL RLS',
               existing_comment='Tenant isolation key -- enforced by PostgreSQL RLS',
               existing_nullable=False)
    op.drop_constraint(None, 'data_quality_records', type_='foreignkey')
    op.alter_column('data_quality_records', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant isolation key — enforced by PostgreSQL RLS',
               existing_comment='Tenant isolation key -- enforced by PostgreSQL RLS',
               existing_nullable=False)
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.alter_column('customers', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant isolation key — enforced by PostgreSQL RLS',
               existing_comment='Tenant isolation key -- enforced by PostgreSQL RLS',
               existing_nullable=False)
    op.drop_constraint(None, 'credit_limit_requests', type_='foreignkey')
    op.alter_column('credit_limit_requests', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant isolation key — enforced by PostgreSQL RLS',
               existing_comment='Tenant isolation key -- enforced by PostgreSQL RLS',
               existing_nullable=False)
    op.drop_constraint(None, 'connector_configs', type_='foreignkey')
    op.alter_column('connector_configs', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant isolation key — enforced by PostgreSQL RLS',
               existing_comment='Tenant isolation key -- enforced by PostgreSQL RLS',
               existing_nullable=False)
    op.drop_constraint(None, 'collection_activities', type_='foreignkey')
    op.alter_column('collection_activities', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant isolation key — enforced by PostgreSQL RLS',
               existing_comment='Tenant isolation key -- enforced by PostgreSQL RLS',
               existing_nullable=False)
    op.drop_constraint(None, 'briefings', type_='foreignkey')
    op.alter_column('briefings', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant isolation key — enforced by PostgreSQL RLS',
               existing_comment='Tenant isolation key -- enforced by PostgreSQL RLS',
               existing_nullable=False)
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.alter_column('audit_logs', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant isolation key — enforced by PostgreSQL RLS',
               existing_comment='Tenant isolation key -- enforced by PostgreSQL RLS',
               existing_nullable=False)
    op.drop_constraint(None, 'agent_run_logs', type_='foreignkey')
    op.alter_column('agent_run_logs', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant isolation key — enforced by PostgreSQL RLS',
               existing_comment='Tenant isolation key -- enforced by PostgreSQL RLS',
               existing_nullable=False)
    # ### end Alembic commands ###
